### ISSUE TITLE
learning curve or pretrained model

### ISSUE THREAD

**Issue by initial-h** [esteveste/dreamerV2-pytorch#2]
Hi, 
Thanks for your reimplementation and open source. I think you must do some tests for these Atari games. I wonder do you have some records of learning curves or pretrained models that I can use to get a baseline score. 
Thanks very much!

**Comment by esteveste** [comment]
Hello, thanks for you issue.
I placed a plot comparing learning the same atari game between the original and this implementation. 
I also placed a link for some pre-trained models.
Hope it helps.
Cheers!
