### ISSUE TITLE
Simple question: How long did it take to train it on Atari?

### ISSUE THREAD

**Issue by jdubkim** [esteveste/dreamerV2-pytorch#5]
Hi thank you so much for an amazing work. I think this is the best pytorch implementation of dreamer out there. Very clean and concise and reproduced similar results to the original implementation. I was simply wondering how long does it take to train this on atari environment. Thank you so much :)

**Comment by esteveste** [comment]
Around 2 days to do 20M steps (5M steps with frameskip) on a RTX 3060 Ti. Pretty slow :)

**Comment by jdubkim** [comment]
@esteveste Thanks a lot, it's quite slow, but at the same time, quite fast compared to Director paper, which is the work based on Dreamer v2 by the same author. Do you remember if the official code was faster than your pytorch implementation or not by any chance? Thank you so much :)

**Comment by esteveste** [comment]
Yes, I tried my best also with fp16 and cura benchmark, but I think I still
was like 10/20 fps off the original implementation.
I could get something like 150fps while the original TF code got 170fps.
But maybe now with Pytorch 2.0 and the compile functionality maybe it could
get better.

**Comment by jdubkim** [comment]
@esteveste oh that's still amazing, I was running with tf but somehow it was very slow (3~5 fps for some reason), so I thought your torch implementation could be much faster. I guess something's wrong with my tensorflow and cuda setup. Thank you so much for help! and the repo is amazing :)

**Comment by esteveste** [comment]
Thanks! :)
